# Form implementation generated from reading ui file 'd:\Documentos\SUPERIOR\4toSEMESTRE\Programacion avanzada\Practicas_\TIENDA_MASCOTAS\MASCOTAS.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 350)
        MainWindow.setMinimumSize(QtCore.QSize(500, 350))
        MainWindow.setMaximumSize(QtCore.QSize(501, 351))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titulo = QtWidgets.QLabel(parent=self.centralwidget)
        self.titulo.setGeometry(QtCore.QRect(120, 40, 281, 61))
        font = QtGui.QFont()
        font.setFamily("Technic")
        font.setPointSize(20)
        font.setBold(True)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.titulo.setFont(font)
        self.titulo.setObjectName("titulo")
        self.titulo_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.titulo_2.setGeometry(QtCore.QRect(-710, 10, 1941, 61))
        font = QtGui.QFont()
        font.setFamily("Technic")
        font.setPointSize(25)
        font.setBold(True)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.titulo_2.setFont(font)
        self.titulo_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.titulo_2.setWordWrap(True)
        self.titulo_2.setObjectName("titulo_2")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(190, 100, 128, 86))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_administrar = QtWidgets.QPushButton(parent=self.widget)
        self.btn_administrar.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_administrar.setObjectName("btn_administrar")
        self.verticalLayout.addWidget(self.btn_administrar)
        self.btn_vender = QtWidgets.QPushButton(parent=self.widget)
        self.btn_vender.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_vender.setObjectName("btn_vender")
        self.verticalLayout.addWidget(self.btn_vender)
        self.btn_reporte = QtWidgets.QPushButton(parent=self.widget)
        self.btn_reporte.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_reporte.setObjectName("btn_reporte")
        self.verticalLayout.addWidget(self.btn_reporte)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titulo.setText(_translate("MainWindow", "Tienda de mascotas"))
        self.titulo_2.setText(_translate("MainWindow", "Pet Shop Adalberto"))
        self.btn_administrar.setText(_translate("MainWindow", "Administrar inventario"))
        self.btn_vender.setText(_translate("MainWindow", "Vender"))
        self.btn_reporte.setText(_translate("MainWindow", "Reporte"))
