# Form implementation generated from reading ui file 'd:\Documentos\SUPERIOR\4toSEMESTRE\Programacion avanzada\Practicas_\PRUEBA\mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
        MainWindow.setMinimumSize(QtCore.QSize(400, 400))
        MainWindow.setMaximumSize(QtCore.QSize(401, 400))
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0 ,y2:1,stop:0 rgba(255, 255, 255, 255), stop:0.5 rgba(214,214,255,255), stop:1 rgba(255,255,255,255));")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 140, 101, 16))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color: transparent;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 190, 101, 16))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("background-color: transparent;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 260, 82, 20))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet("background-color: transparent;")
        self.label_3.setObjectName("label_3")
        self.comboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(160, 260, 61, 20))
        self.comboBox.setStyleSheet("background-color: transparent;\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 30, 140, 90))
        self.label_4.setStyleSheet("background-color: transparent;\n"
"border: 2px solid black;\n"
"border-image: url(:/cct/logo3.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(130, 20, 140, 100))
        self.label_5.setStyleSheet("border: 1px solid black;\n"
"background-color: transparent;\n"
"border-radius: 10px;\n"
"")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.Ingresar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Ingresar.setGeometry(QtCore.QRect(160, 330, 80, 24))
        self.Ingresar.setObjectName("Ingresar")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(110, 160, 180, 22))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(110, 210, 180, 22))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Usuario:"))
        self.label_2.setText(_translate("MainWindow", "Servidor:"))
        self.label_3.setText(_translate("MainWindow", "Status: "))
        self.comboBox.setItemText(0, _translate("MainWindow", "Online"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Offline"))
        self.Ingresar.setText(_translate("MainWindow", "Ingresar"))
